### ISSUE TITLE
Please tag latest version

### ISSUE THREAD

**Issue by bacongravy** [bruceCzK/emoji-generator#3]
Hello! Thank you for this project.

I am trying to load assets from this repository using the JSDelivr CDN, however the latest tagged version 0.3.0 is from 2017. Please tag `master` with a new version number (0.4.0 would be fine).

As a workaround I am pinning to `master`:
https://cdn.jsdelivr.net/gh/bruceCzK/Emojiii@master/images/joy-pixels/1f389.png

But I would prefer to pin to a specific version.

**Comment by bruceCzK** [comment]
0.4.0 released with images updated

**Comment by bacongravy** [comment]
Thanks! In case you're curious, I'm using it [here](https://github.com/bacongravy/emoji-favicon-cli/blob/9064678d0e40684b08993cc680dd3552587d0e21/src/providers/emojiii.js#L9) in the [emoji-favicon-cli](https://github.com/bacongravy/emoji-favicon-cli) project.
